### ISSUE TITLE
Escolha de site para o projeto

### ISSUE THREAD

**Issue by izabellaalves** [Interacao-Humano-Computador/2023.2-Grupo01#1]
# Escolha de site para o projeto
# Descrição
Nesta issue, vamos realizar a seleção do site que será utilizado para o trabalho da disciplina de Interação Humano-Computador. Cada membro do grupo deve escolher um site e, juntos, decidiremos qual deles é o mais adequado para o projeto. Além disso, é essencial que todos assistam aos vídeos disponibilizados pelo professor sobre a escolha do site, para garantir que tenhamos uma compreensão sólida das diretrizes a seguir e dos critérios de seleção.
# Atividades 

- [x] Assistir aos vídeos disponibilizados pelo professor. Disponível em: [https://www.youtube.com/watch?v=uNojIJ1UhI4](url)
- [x] Realizar pesquisa e escolher o site _(Gabriel Rosa)_
- [x] Realizar pesquisa e escolher o site _(Gabriel Zaranza)_
- [x] Realizar pesquisa e escolher o site _(Izabella Alves)_
- [x] Realizar pesquisa e escolher o site _(Lucas de Oliveira)_
- [x] Realizar pesquisa e escolher o site _(Lucas Ribeiro)_
- [x] Realizar pesquisa e escolher o site _(Lucas Victor)_
- [x] Realizar pesquisa e escolher o site _(Zenilda Pedrosa)_

**Comment by izabellaalves** [comment]
O site analisado e escolhido por mim foi o site da [PDCF (Polícia Civil do Distrito Federal)](https://www.pcdf.df.gov.br/). O site foi escolhido pela dificuldade de se navegar e achar os serviços necessários no site, a página inicial é carregada e o design das páginas que são abertas ao clicar é muito simplificado, não distingue título de conteúdo, entre outros.

**Comment by gabrielrosa09** [comment]
O site e aplicativo por mim é o [Calibre E-book Management](https://calibre-ebook.com/). Ele é um gerenciador de eBooks de código aberto que ajuda a organizar e converter eBooks em diferentes formatos. O motivo da escolha é devido ele ser bem simples, se parecendo muito com os sites e apps à moda antiga e possuindo poucas funcionalidades e não possui nenhuma acessibilidade. Além da paleta de cores, não combina de forma alguma.

**Comment by LucasOliveiraDiasMarquesFerreira** [comment]
O site que eu escolhi foi o do https://www.detran.df.gov.br/ Este é o site do tribunal de justiça do DF e pessoalmente achei muito desorganizado e muito poluído visualmente, não é um site que eu como usuário acharia agradável a navegação e nem teria facilidade de estar encontrando informações especificas nele.

**Comment by Lucas13032003** [comment]
O site e aplicativo por mim é o [Nota Legal DF](https://www.notalegal.df.gov.br/) "Nota Legal" é um programa que recompensa as pessoas por pagarem impostos e emitirem notas fiscais, mas tem alguns defeitos relacionados à interface são problemas na aparência e usabilidade de um sistema ou aplicativo, tornando-o difícil de usar, confuso, lento, não responsivo a diferentes dispositivos, com anúncios intrusivos, falta de feedback e problemas visuais. Corrigir esses defeitos é essencial para melhorar a experiência do usuário.

**Comment by GZaranza** [comment]
O site que eu escolhi é o https://pandas.pydata.org da biblioteca python Pandas. O site não oferece nenhuma forma de acessibilidade, tem a página principal com muitos elementos e mal distribuídos.

**Comment by lucassouzs** [comment]
O site que eu escolhi, foi o do [Alistamento Militar](https://alistamento.eb.mil.br/), do Exército Brasileiro. No site do alistamento militar, é notável diversos defeitos que podem afetar a experiência dos usuários. Isso inclui problemas de acesso, segurança, usabilidade e desempenho. Esses defeitos podem abranger dificuldades no registro, lentidão, erros de funcionamento, falta de atualizações e suporte insuficiente. Identificar e corrigir esses defeitos é fundamental para melhorar a funcionalidade e proporcionar uma experiência mais suave aos usuários do site do alistamento militar.

**Comment by ZenildaVieira** [comment]
O site que eu escolhi foi o [MPDFT](https://www.mpdft.mp.br/portal/) pela aparência confusa dos menus e da distribuição das informações.
