### ISSUE TITLE
Criação de personas

### ISSUE THREAD

**Issue by izabellaalves** [Interacao-Humano-Computador/2023.2-Grupo01#10]
# Criação de personas
## Descrição
As personas são representações fictícias de segmentos de usuários reais, criadas para melhor compreender as necessidades, comportamentos e motivações dos usuários de um determinado produto ou serviço. Neste caso, estamos focando em criar quatro personas para os usuários do Programa Nota Legal, cada uma representando um perfil diferente, incluindo a antipersona que representa um perfil negativo.
## Tarefas

- [x] Criar uma persona primária
- [x] Criar uma persona secundária
- [x] Criar uma persona terciária (Se identificada)
- [x] Criar uma antipersona
- [x] Documentar o que foi criado num documento markdown

## Lembre-se de checar se o github pages possui:
- [x] O histórico de versão padronizado.
- [x] O(s) autor(es) e o(s) revisor(es) para cada artefato.
- [x] Referências bibliográficas e/ou bibliografia em todos os artefatos.
- [x] As tabelas e imagens  (se houver) possuem legenda e fonte e elas chamadas dentro dos texto.
- [x] Um texto fazendo uma introdução dos artefatos, por exemplo das “Ferramentas”.

**Comment by Lucas13032003** [comment]
OBS.: não identificamos personas terciaras.
