### ISSUE TITLE
Documento de lista de sites avaliados

### ISSUE THREAD

**Issue by izabellaalves** [Interacao-Humano-Computador/2023.2-Grupo01#2]
# Documento de lista de sites avaliados
# Descrição
Esta issue tem como objetivo compartilhar as avaliações individuais dos membros da equipe sobre os sites que eles escolheram para o projeto de Interação Humano-Computador. O propósito é entender melhor as características e elementos de design de cada site, identificar áreas de melhoria e determinar como eles podem servir como exemplos relevantes para o nosso projeto.
# Tarefas

- [x] Acessar o documento "lista-sites-avaliados.md", que se encontra na pasta "planejamento do projeto", dentro da pasta "doc"
- [x] Adicionar o site avaliado por você
- [x] Modificar o status de revisão

# Observação
Todos são responsáveis por essa issue, então é necessário deixar um comentário quando terminar de cumpri-la. Assim que todos terminarem, a issue será fechada.

**Comment by izabellaalves** [comment]
Site da PCDF adicionado na lista de sites avaliados.

**Comment by gabrielrosa09** [comment]
Site do Calibre adicionado na lista de sites avaliados.

**Comment by Lucas13032003** [comment]
Site Nota Legal adicionado
