### ISSUE TITLE
Documento do processo de design

### ISSUE THREAD

**Issue by izabellaalves** [Interacao-Humano-Computador/2023.2-Grupo01#5]
# Documento do processo de design
# Descrição
Esta issue tem como objetivo documentar o conceito de processo de design, identificar os tipos de processos de design existentes e registrar qual processo foi escolhido pela equipe para ser adotado no nosso projeto de Interação Humano-Computador.
# Tarefas

- [x] Verificar o documento dos semestres anteriores
- [x] Criar o documento "processo-de-design.md", na pasta "planejamento do projeto", dentro da pasta "doc"
- [x] Descrever o que é design, o que é um processo de design, identificar os tipos de processo e registrar o escolhido pela equipe
- [x] Adicionar histórico de versões e referências.

**Comment by Lucas13032003** [comment]
Issue finalizada
