### ISSUE TITLE
Perfil do Usuário - Grupo de Foco

### ISSUE THREAD

**Issue by izabellaalves** [Interacao-Humano-Computador/2023.2-Grupo01#8]
# Perfil do Usuário - Grupo de Foco
## Descrição 
O Programa Nota Legal tem como objetivo incentivar a emissão de notas fiscais legais por parte dos consumidores. O objetivo desta issue é organizar e conduzir um grupo de foco com usuários do Programa Nota Legal. O grupo de foco possibilitará a identificação de padrões, motivações e desafios enfrentados pelos usuários, ajudando a adaptar e otimizar o programa para atender melhor às suas necessidades.
## Tarefas

- [x] Montar roteiro do grupo de foco
- [x] Participar da reunião segunda-feira 19:30
- [x] Documentar

**Comment by Lucas13032003** [comment]
Perfil de Usuário:

Idade: 46 a 60 anos
Sexo: Ambos os sexos (Masculino/Feminino)
Escolaridade: Superior completo
Afinidade com tecnologia: Média
Frequência: Frequente
Acesso: Computador e Celular (Ambos)
Objetivo: Realizar indicações
